[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mytest"
version = "0.1.0"
description = "Progetto Python di esempio"
readme = "README.md"
requires-python = ">=3.8"
authors = [
  { name = "Daniele Speziale" }
]
dependencies = []
